github:
  - "minuxlintebiandedition"
paypal:
  - "https://paypal.me/Julian Pursell"
#patreon:
#  - "YourPatreonName"
#ko_fi:
#  - "YourKoFiName"
#open_collective:
#  - "your-open-collective-name"
#liberapay:
#  - "your-liberapay-name"
#tidelift:
#  - "your-tidelift-name"
